made the text and link for the twitter share dynamic
NEAR-Edu/stats.gallery pull request #72
Opened 2021-11-09 01:37 UTC by jhammond2012

2021-11-09 18:06 UTC, encody commented
Part of the issue is that the Twitter button code actually *replaces* the HTML in the page with an `<iframe>`, so the computed properties don't update on page navigation because the target element no longer exists (i.e. it has been replaced with Twitter's custom code). One solution to this problem would be to replace [this code](https://github.com/NEAR-Edu/stats.gallery/blob/main/src/views/Page.vue#L23-L33) with a dynamically *re-generated* bit of HTML code that we stick into a [`v-html`](https://v3.vuejs.org/guide/template-syntax.html#raw-html) binding, and then [re-run the Twitter button replacer code](https://github.com/NEAR-Edu/stats.gallery/blob/main/src/App.vue#L115-L122).

2021-11-09 21:03 UTC, jhammond2012 commented
@encody I have updated this to rerender on route change.

2021-11-09 22:01 UTC, encody requested changes

2021-11-09 22:01 UTC, encody commented on src/views/Page.vue
> +      shareLink = `https://twitter.com/share?ref_src=${
Could this be simplified to a single `return` statement?

2021-11-09 22:01 UTC, encody commented on src/views/Page.vue
> +      tweetButton: '',
Prefer `ref` (composition API)

2021-11-09 22:01 UTC, encody commented on src/views/Page.vue
> +  },
Prefer composition API

2021-11-09 22:03 UTC, encody commented
The Tweet button does not appear when loading the overview page from the landing page.


![2021-11-09-16-02-51](https://user-images.githubusercontent.com/7459638/141012135-93ee5449-170d-4536-8f4b-769c775ec5b9.gif)

2021-11-09 22:06 UTC, encody commented on src/views/Page.vue
> +      if (routeSlug == 'quests') tweetText = 'Check out my quests on NEAR!';
Could this be a switch/case, or even an object that maps route slugs to messages? Might be a little more readable that way.

2021-11-09 22:07 UTC, encody commented on src/views/Page.vue
> +      const routeSlug = routeArr[routeArr.length - 1];
Instead of route slug, you might be able to use the route's name.

2021-11-10 14:49 UTC, jhammond2012 reviewed
Changes have been made and committed to this branch.

2021-11-10 15:59 UTC, encody approved these changes

2021-11-10 18:45 UTC, merged